#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: kube-tools install <Target> <Version> [Options]

Targets
    master
    worker

    kubeadm
    kubelet
    kubectl

    crictl
    calicoctl
    cni-plugins

    images-master
    images-worker

    templates-<Component>

Options
    --arch=<Architecture>
    --templates-<Component>=<Templates>

Components
    kubeadm
    calico
    multus-cni
    vxlan-controller
    kubealived
    user-admin-crb
EOF
)

function main {
    local COMMAND="$1"
    local TARGET="$2"
    local VERSION="$3"
    local TEMPLATE_NAME="${TARGET#templates-}"
    local ARCH=amd64
    local TEMPLATES

    if [ -z "${VERSION}" ]; then usage; fi

    shift 3
    for ARG in "$@"; do
        case "${ARG}" in
            --arch=*) ARCH="${ARG#*=}" ;;
            --templates-*=*) TEMPLATES="${TEMPLATES} ${ARG#--templates-}" ;;
            *) unknown_option "${ARG}" ;;
        esac
    done

    local START_TIME; START_TIME="$(start_time)"
    case "${COMMAND} ${TARGET}" in
        "install master"|\
        "install images-master")
            install_"${TARGET//-/_}" "${VERSION}" \
                                     "${TEMPLATES}" \
                                     "${ARCH}" ;;
        "install worker"|\
        "install images-worker")
            install_"${TARGET//-/_}" "${VERSION}" \
                                     "${TEMPLATES}" \
                                     "${ARCH}" ;;
        "install kubeadm"|\
        "install kubelet"|\
        "install kubectl"|\
        "install crictl"|\
        "install calicoctl"|\
        "install cni-plugins")
            install_"${TARGET//-/_}" "${VERSION}" "${ARCH}"
        ;;
        "install templates-${TEMPLATE_NAME}")
            install_templates "$(templates "${TEMPLATE_NAME}" "${TEMPLATES}")"
        ;;
        *) usage ;;
    esac
    show_completion_time "${START_TIME}"
}

function kube_tools_binaries {
    local VERSION="$1"
    local ARCH="$2"
    printf %b "https://storage.googleapis.com/kubernetes-release/release/" \
              "${VERSION}/bin/linux/${ARCH}"
}
function kube_tools_configs {
    local VERSION="$1"
    printf %b "https://raw.githubusercontent.com/kubernetes/kubernetes/" \
              "${VERSION}/build/debs"
}
function crictl_archive {
    local VERSION="$1"
    local ARCH="$2"
    printf %b "https://github.com/kubernetes-incubator/cri-tools/" \
              "releases/download/${VERSION}/" \
              "crictl-${VERSION}-linux-${ARCH}.tar.gz"
}
function calicoctl_binary {
    local VERSION="$1"
    printf %b "https://github.com/projectcalico/calicoctl/" \
              "releases/download/${VERSION}/calicoctl"
}
function cni_plugins_archive {
    local VERSION="$1"
    local ARCH="$2"
    printf %b "https://github.com/containernetworking/plugins/" \
              "releases/download/${VERSION}/" \
              "cni-plugins-${ARCH}-${VERSION}.tgz"
}
function templates {
    local Name="$1"
    local Templates="$2"

    local Manifests; Manifests="$(printf %b \
        "https://raw.githubusercontent.com/travelping/cennsonic" \
        "/master/kube/manifests" \
    )"

    case "${Name}" in
        kubeadm) template "${Name}" "${Templates}" \
            "$(printf %b "${Manifests}/config/kubeadm.yaml")"
        ;;
        calico) template "${Name}" "${Templates}" \
            "$(printf %b " ${Manifests}/network/calico-etcd.yaml" \
                         " ${Manifests}/network/calico-etcd-rbac.yaml" \
                         " ${Manifests}/network/calico-etcd-config.yaml" \
                         " ${Manifests}/network/calico-etcd-sync.yaml")" \
#                        " ${Manifests}/network/calico-kdd.yaml" \
#                        " ${Manifests}/network/calico-kdd-rbac.yaml")"
        ;;
        multus-cni) template "${Name}" "${Templates}" \
            "$(printf %b " ${Manifests}/network/multus-cni.yaml" \
                         " ${Manifests}/network/multus-cni-rbac.yaml" \
                         " ${Manifests}/network/multus-cni-config.yaml")"
        ;;
        vxlan-controller) template "${Name}" "${Templates}" \
            "$(printf %b " ${Manifests}/network/kube-vxlan-controller.yaml")"
        ;;
        kubealived) template "${Name}" "${Templates}" \
            "$(printf %b "${Manifests}/network/kubealived.yaml")"
        ;;
        user-admin-crb) template "${Name}" "${Templates}" \
            "$(printf %b "${Manifests}/users/user-admin-crb.yaml")"
        ;;
    esac
}
function template {
    local Name="$1"
    local Templates; read -r -a Templates <<< "${2//;/ }"
    local Default="$3"

    local Template
    for Template in "${Templates[@]}"; do
        local TemplateName="${Template%%=*}"
        local TemplateFiles="${Template#*=}"

        if [ "${Name}" = "${TemplateName}" ]; then
            echo "${TemplateFiles//,/ }"
            return
        fi
    done

    echo "${Default}"
}
function master_images {
    local KUBERNETES_VERSION="$1"
    local TEMPLATES="$2"
    local ARCH="$3"

    /opt/bin/kubeadm config images list \
        --kubernetes-version "${KUBERNETES_VERSION}"

    template_images calico "${TEMPLATES}"
    template_images multus-cni "${TEMPLATES}"
    template_images vxlan-controller "${TEMPLATES}"
    template_images kubealived "${TEMPLATES}"
}
function worker_images {
    local KUBERNETES_VERSION="$1"
    local TEMPLATES="$2"
    local ARCH="$3"

    /opt/bin/kubeadm config images list \
                     --kubernetes-version "${KUBERNETES_VERSION}" \
        |
        grep -E "kube-proxy|pause|coredns"

    template_images calico "${TEMPLATES}" | grep -v calico/kube-controllers
    template_images multus-cni "${TEMPLATES}"
    template_images vxlan-controller "${TEMPLATES}"
}
function template_images {
    local NAME="$1"
    local TEMPLATES="$2"

    local TEMPLATE
    for TEMPLATE in $(templates "${NAME}" "${TEMPLATES}"); do
        read_template "${TEMPLATE}"
    done | grep image: | sort -u | sed "s/.*: //"
}

function install_master {
    local KUBERNETES_VERSION="$1"
    local TEMPLATES="$2"
    local ARCH="$3"

    install_kubeadm "${KUBERNETES_VERSION}" "${ARCH}" 
    install_kubelet "${KUBERNETES_VERSION}" "${ARCH}"
    install_kubectl "${KUBERNETES_VERSION}" "${ARCH}"
    install_images master "${KUBERNETES_VERSION}" "${TEMPLATES}" "${ARCH}"

    install_templates "$(templates kubeadm "${TEMPLATES}")" \
                      "$(templates calico "${TEMPLATES}")" \
                      "$(templates multus-cni "${TEMPLATES}")" \
                      "$(templates vxlan-controller "${TEMPLATES}")" \
                      "$(templates kubealived "${TEMPLATES}")" \
                      "$(templates user-admin-crb "${TEMPLATES}")"

    enable_service docker kubelet
}
function install_worker {
    local KUBERNETES_VERSION="$1"
    local TEMPLATES="$2"
    local ARCH="$3"

    install_kubeadm "${KUBERNETES_VERSION}" "${ARCH}"
    install_kubelet "${KUBERNETES_VERSION}" "${ARCH}"
    install_kubectl "${KUBERNETES_VERSION}" "${ARCH}"
    install_images worker "${KUBERNETES_VERSION}" "${TEMPLATES}" "${ARCH}"

    enable_service docker kubelet
}

function install_kubeadm {
    local VERSION="$1"
    local ARCH="$2"

    log "Installing kubeadm ${VERSION} ${ARCH}..."
    install_binary "$(kube_tools_binaries "${VERSION}" "${ARCH}")/kubeadm"
    install_config "$(kube_tools_configs "${VERSION}")/10-kubeadm.conf" \
                    /etc/systemd/system/kubelet.service.d 644
}
function install_kubelet {
    local VERSION="$1"
    local ARCH="$2"

    log "Installing kubelet ${VERSION} ${ARCH}..."
    install_binary "$(kube_tools_binaries "${VERSION}" "${ARCH}")/kubelet"
    install_config "$(kube_tools_configs "${VERSION}")/kubelet.service" \
                    /etc/systemd/system 444
}
function install_kubectl {
    local VERSION="$1"
    local ARCH="$2"

    log "Installing kubectl ${VERSION} ${ARCH}..."
    install_binary "$(kube_tools_binaries "${VERSION}" "${ARCH}")/kubectl"
}
function install_crictl {
    local VERSION="$1"
    local ARCH="$2"

    log "Installing crictl ${VERSION} ${ARCH}..."
    install_binary_archive "$(crictl_archive "${VERSION}" "${ARCH}")"
}
function install_calicoctl {
    local VERSION="$1"

    log "Installing calicoctl ${VERSION}..."
    install_binary "$(calicoctl_binary "${VERSION}")"
}
function install_cni_plugins {
    local VERSION="$1"
    local ARCH="$2"

    log "Installing CNI plugins ${VERSION} ${ARCH}..."
    install_binary_archive "$(cni_plugins_archive "${VERSION}" "${ARCH}")" \
                           /opt/cni/bin
}
function install_images_master {
    install_images master "$@"
}
function install_images_worker {
    install_images worker "$@"
}
function install_images {
    local NODE_TYPE="$1"
    shift

    log "Pulling ${NODE_TYPE} images..."
    for IMAGE in $("${NODE_TYPE}_images" "$@"); do
        docker pull "${IMAGE}"
    done
}

function file_digest {
    local HASH_FUN="$1"
    local FILENAME="$2"
    openssl "${HASH_FUN}" "${FILENAME}" | sed "s/.*= //"
}
function install_binary {
    local URL="$1"
    local DEST="${2:-/opt/bin}"
    local BINARY; BINARY=$(basename "${URL}")
    local REMOTE_DIGEST
    local LOCAL_DIGEST
    local HASH_FUN="sha1"

    REMOTE_DIGEST="$(curl -L "${URL}.${HASH_FUN}")"
    if [ -e "${DEST}/${BINARY}" ]; then
        LOCAL_DIGEST="$(file_digest "${HASH_FUN}" "${DEST}/${BINARY}")"
    fi

    if [ "${LOCAL_DIGEST}" != "${REMOTE_DIGEST}" ]; then
        curl -LO "${URL}"
        sudo mkdir -p "${DEST}"
        sudo install "${BINARY}" "${DEST}" && rm "${BINARY}"
    fi

    echo "Digest: ${HASH_FUN}:$(file_digest sha1 "${DEST}/${BINARY}")"
}
function install_binary_archive {
    local URL="$1"
    local DEST="${2:-/opt/bin}"
    local TMPDIR; TMPDIR=$(basename "${URL}")

    mkdir -p "${TMPDIR}"
    curl -L "${URL}" | tar -C "${TMPDIR}" -xz
    sudo mkdir -p "${DEST}"
    sudo install "$(find "${TMPDIR}" -type f)" "${DEST}"
    rm "$(find "${TMPDIR}" -type f)"
    rmdir "${TMPDIR}"
}
function install_config {
    local URL="$1"
    local DEST="$2"
    local MODE="$3"
    local CONFIG; CONFIG=$(basename "${URL}")

    sudo mkdir -p "${DEST}"
    curl -sL "${URL}" | sed "s:/usr/bin:/opt/bin:g" | \
                        sudo tee "${DEST}/${CONFIG}" > /dev/null
    sudo chmod "${MODE}" "${DEST}/${CONFIG}"
}
function install_templates {
    local FILE_NAMES=$*
    local FILE_NAME
    local TEMPLATES_DIR="/etc/kubernetes/templates"

    sudo mkdir -m 700 -p "${TEMPLATES_DIR}"
    for FILE_NAME in ${FILE_NAMES}; do
        local BASE_NAME; BASE_NAME="$(basename "${FILE_NAME}")"

        log "Installing ${FILE_NAME} as ${BASE_NAME}..."
        read_template "${FILE_NAME}" |
            sudo tee "${TEMPLATES_DIR}/${BASE_NAME}" > /dev/null
        sudo chmod 600 "${TEMPLATES_DIR}/${BASE_NAME}"
    done
}
function read_template {
    local Template="$1"

    if [ -e "${Template}" ]; then cat "${Template}"; return; fi
    curl -sL "${Template}"
}

function enable_service {
    local SERVICES="$*"

    for SERVICE in ${SERVICES}; do
        log "Enabling ${SERVICE}..."
        sudo systemctl enable "${SERVICE}"
    done
}

function node_name {
    sed "s/\\..*//" /etc/hostname
}

function start_time {
    date +%s
}
function show_completion_time {
    local START_TIME="$1"
    local END_TIME; END_TIME="$(date +%s)"
    log "Complete in $(date -d@$((END_TIME - START_TIME)) -u +%Mm%Ss)."
}
function log {
    echo "$(date -uIseconds | sed s/\+.*//) [$(node_name)]" "$@"
}
function usage {
    >&2 echo "${USAGE}"
    exit 2
}
function unknown_option {
    local OPTION="$1"
    >&2 echo "Unknown option: ${OPTION%%=*}"
    exit 2
}

main "$@"
