#!/bin/bash

set -e

USAGE="Usage: kube-pki <[User@]From> <[User@]To>"

function main {
    local FROM="$1"
    local TO="$2"
    local ARCHIVE="/tmp/pki.tgz"

    if [ -z "${FROM}" ] || [ -z "${TO}" ]; then usage; fi

    ssh "${FROM}" bash -s < "$(workdir)/kube-node" master pki make "${ARCHIVE}"
    scp -3 "${FROM}:${ARCHIVE}" "${TO}:${ARCHIVE}"
    ssh "${FROM}" rm \\"${ARCHIVE}"
    ssh "${TO}" bash -s < "$(workdir)/kube-node" master pki install "${ARCHIVE}"
}

function workdir {
    dirname "$0"
}

function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
