#!/bin/bash

set -e

# shellcheck source=src/kube-utils
source "$(dirname "$0")/kube-utils"

KUBE_VERSION="v1.12.7"

Usage=$(cat <<EOF
Usage: kube-make <Action> [Options]

Actions:
    prepare
    download
    install

Options:
    --master=<[SshUser@]SshAddress[/NodeIp]>  # if Node Ip is not provided
    --worker=<[SshUser@]SshAddress[/NodeIp]>  # SSH Address will be used as one

Options (prepare):
    --os=<coreos|centos|ubuntu>  # (default: coreos)
    --setup-user=<UserName>

Options (download):
    --kube-version=<Version>     # (default: ${KUBE_VERSION})

Options (install):
    --init
    --api-ip=<ApiIp>
    --vrrp-iface=<Iface>
    --admin-user=<UserName>      # (default: $(whoami))
    --master-ssh=<[SshUser@]SshAddress>
EOF
)

function main {
    local Action="$1"
    local Masters
    local Workers

    if [ -z "${Action}" ]; then stop "${Usage}"; fi

    shift
    local Arg
    for Arg in "$@"; do
        case "${Arg}" in
            --master=*) local Masters="${Masters} ${Arg##*=}";;
            --worker=*) local Workers="${Workers} ${Arg##*=}";;
            --os=*) local Os="${Arg##*=}";;
            --init) local Init=true ;;
            --api-ip=*) local ApiIp="${Arg##*=}";;
            --vrrp-iface=*) local VrrpIface="${Arg##*=}";;
            --setup-user=*) local SetupUser="${Arg##*=}";;
            --master-ssh=*) local MasterSsh="${Arg##*=}";;
            --admin-user=*) local AdminUser="${Arg##*=}";;
            --kube-version=*) local KubeVersion="${Arg##*=}";;
            *) stop unknown-option "${Arg}";;
        esac
    done

    Masters="${Masters//,/ }"
    Workers="${Workers//,/ }"
    Os="${Os:-coreos}"
    Init="${Init:-false}"
    AdminUser="${AdminUser:-$(whoami)}"
    KubeVersion="${KubeVersion:-${KUBE_VERSION}}"

    case "${Action}" in
        prepare) make_prepare "${Masters}" "${Workers}" \
                              "${Os}" "${SetupUser}" ;;

        download) make_download "${Masters}" "${Workers}" "${KubeVersion}" ;;

        install) make_install "${Masters}" "${Workers}" \
                              "${ApiIp}" "${VrrpIface}" \
                              "${Init}" "${MasterSsh}" "${AdminUser}" ;;
        *) stop "${Usage}" ;;
    esac

    wait
}

function make_prepare {
    local Masters; read -r -a Masters <<< "$1"
    local Workers; read -r -a Workers <<< "$2"
    local Os="$3"
    local SetupUser="$4"

    case "${Os}" in
        centos|ubuntu) ;;
        *) exit 0 ;;
    esac

    local Node
    for Node in "${Masters[@]}" "${Workers[@]}"; do
        run "tools-${Os}" "$(node_ssh "${Node}")" \
            install --setup-user="${SetupUser}" &
    done
}

function make_download {
    local Masters; read -r -a Masters <<< "$1"
    local Workers; read -r -a Workers <<< "$2"
    local KubeVersion="$3"

    local Master
    for Master in "${Masters[@]}"; do
        run tools "$(node_ssh "${Master}")" install master "${KubeVersion}" &
    done
    local Worker
    for Worker in "${Workers[@]}"; do
        run tools "$(node_ssh "${Worker}")" install worker "${KubeVersion}" &
    done
}

function make_install {
    local Masters; read -r -a Masters <<< "$1"
    local Workers; read -r -a Workers <<< "$2"
    local ApiIp="$3"
    local VrrpIface="$4"
    local Init="$5"
    local MasterSsh="$6"
    local AdminUser="$7"

    if "${Init}"; then
        local Master0Ssh; Master0Ssh="$(node_ssh "${Masters[0]}")"
        local Master0Ip; Master0Ip="$(node_ip "${Masters[0]}")"

        if [ -z "${ApiIp}" ]; then ApiIp="${Master0Ip}"; fi
        if [ -z "${MasterSsh}" ]; then MasterSsh="${Master0Ssh}"; fi

        run node "${Master0Ssh}" \
                 master init "${Master0Ip}" "${ApiIp}" \
                        --vrrp-iface="${VrrpIface}"

        run user "${Master0Ssh}" create "${AdminUser}" -a

        scp "${Master0Ssh}:${AdminUser}.conf" ./
        ssh "${Master0Ssh}" rm \\"${AdminUser}.conf"

        Masters=("${Masters[@]:1}")
    fi

    local Master
    for Master in "${Masters[@]}"; do
        "$(workdir)/kube-pki" "${MasterSsh}" "$(node_ssh "${Master}")"
        run node "$(node_ssh "${Master}")" \
                 master join "$(node_ip "${Master}")" "${ApiIp}"
    done &

    if [ "${#Workers[@]}" -gt 0 ]; then
        local JoinInfo; JoinInfo=$(run node "${MasterSsh}" master join-info)
    fi

    local Worker
    for Worker in "${Workers[@]}"; do
        run node "$(node_ssh "${Worker}")" \
                 worker join "$(node_ip "${Worker}")" "${ApiIp}" "${JoinInfo}" &
    done
}

function node_ssh {
    echo "${1%%/*}"
}
function node_ip {
    local Ip="${1##*@}"
    echo "${Ip##*/}"
}

main "$@"
