#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: kube-user <Action> <Username> [Options]

Actions
    create
    delete

Options
    -a, --admin
    -c, --company=<Company>
    -d, --days=<Days>
    -s, --server=<Server>
    -p, --port=<Port>
    -C, --cluster=<Cluster Name>
        --ca-cert=<CA Cert Path>
        --ca-cert-key=<CA Cert Key Path>
EOF
)

function main {
    case "$1 $2" in
        "create $2"|\
        "delete $2")
            local ACTION="$1"
            local USERNAME="$2"
            shift 2

            if [ -z "${USERNAME}" ]; then usage; fi
            "${ACTION}_user" "${USERNAME}" "$@"
        ;;
        *) usage ;;
    esac
}

function ca_cert {
    echo "/etc/kubernetes/pki/ca.crt"
}
function ca_cert_key {
    echo "/etc/kubernetes/pki/ca.key"
}
function templates {
    echo "/etc/kubernetes/templates"
}
function kubectl {
    sudo -H /opt/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf "$@"
}

function create_user {
    local USERNAME="$1"
    shift

    for ARG in "$@"; do
        case "${ARG}" in
            -a|--admin) local ADMIN=true; shift ;;
            -c=*|--company=*) local COMPANY="${ARG#*=}"; shift ;;
            -d=*|--days=*) local DAYS="${ARG#*=}"; shift ;;
            -s=*|--server=*) local SERVER="${ARG#*=}"; shift ;;
            -p=*|--port=*) local PORT="${ARG#*=}"; shift ;;
            -C=*|--cluster=*) local CLUSTER="${ARG#*=}"; shift ;;
                 --ca-cert=*) local CA_CERT="${ARG#*=}"; shift ;;
                 --ca-cert-key=*) local CA_CERT_KEY="${ARG#*=}"; shift ;;
            *=*) >&2 echo "Unknown argument: ${ARG%=*}"; exit 2 ;;
            *) >&2 echo "Unknown argument: ${ARG}"; exit 2 ;;
        esac
    done

    log "Creating user ${USERNAME}..."

    ADMIN="${ADMIN:-false}"
    COMPANY="${COMPANY:-Kubernetes}"
    DAYS="${DAYS:-365}"
    NAMESPACE="${NAMESPACE:-default}"
    SERVER="${SERVER:-k8s.$(cluster_name)}"
    PORT="${PORT:-6443}"
    CLUSTER="${CLUSTER:-$(cluster_name)}"
    CA_CERT="${CA_CERT:-$(ca_cert)}"
    CA_CERT_KEY="${CA_CERT_KEY:-$(ca_cert_key)}"

    create_cert_key "${USERNAME}"
    create_cert "${USERNAME}" "${COMPANY}"
    sign_cert "${USERNAME}" "${DAYS}" "${CA_CERT}" "${CA_CERT_KEY}"
    create_kubeconfig "${USERNAME}" "${NAMESPACE}" \
                      "${SERVER}" "${PORT}" "${CLUSTER}" "${CA_CERT}"
    delete_cert "${USERNAME}"
    delete_cert_key "${USERNAME}"

    if "${ADMIN}"; then create_admin_binding "${USERNAME}"; fi
}
function delete_user {
    local USERNAME="$1"
    shift

    log "Deleting user ${USERNAME}..."
    delete_admin_binding "${USERNAME}"
}

function create_cert_key {
    local USERNAME="$1"
    openssl genrsa -out "${USERNAME}.key" 2048
}
function delete_cert_key {
    local USERNAME="$1"
    rm "${USERNAME}.key"
}
function create_cert {
    local USERNAME="$1"
    local COMPANY="$2"

    openssl req -new \
                -key "${USERNAME}.key" \
                -out "${USERNAME}.crt" \
                -subj "/CN=${USERNAME}/O=${COMPANY}"
}
function sign_cert {
    local USERNAME="$1"
    local DAYS="$2"
    local CA_CERT="$3"
    local CA_CERT_KEY="$4"

    sudo openssl x509 -req \
                      -in "${USERNAME}.crt" \
                      -CA "${CA_CERT}" \
                      -CAkey "${CA_CERT_KEY}" \
                      -CAcreateserial \
                      -out "${USERNAME}.pem" \
                      -days "${DAYS}"
}
function delete_cert {
    local USERNAME="$1"
    rm "${USERNAME}.crt"
    rm "${USERNAME}.pem"
}

function create_kubeconfig {
    local USERNAME="$1"
    local NAMESPACE="$2"
    local SERVER="$3"
    local PORT="$4"
    local CLUSTER="$5"
    local CA_CERT="$6"
    local KUBECONFIG="${USERNAME}.conf"

    /opt/bin/kubectl config set-cluster "${CLUSTER}" \
        --kubeconfig="${KUBECONFIG}" \
        --server="$(server_endpoint "${SERVER}" "${PORT}")" \
        --certificate-authority="${CA_CERT}" \
        --embed-certs=true
    
    /opt/bin/kubectl config set-credentials "${USERNAME}-${CLUSTER}" \
        --kubeconfig="${KUBECONFIG}" \
        --client-certificate="${USERNAME}.pem" \
        --client-key="${USERNAME}.key" \
        --embed-certs=true
    
    /opt/bin/kubectl config set-context "${USERNAME}-${CLUSTER}" \
        --kubeconfig="${KUBECONFIG}" \
        --cluster="${CLUSTER}" \
        --user="${USERNAME}-${CLUSTER}" \
        --namespace="${NAMESPACE}"
    
    /opt/bin/kubectl config use-context "${USERNAME}-${CLUSTER}" \
        --kubeconfig="${KUBECONFIG}"
}
function create_admin_binding {
    admin_binding apply "$@"
}
function delete_admin_binding {
    admin_binding delete "$@"
}
function admin_binding {
    local ACTION="$1"
    local USERNAME="$2"

    sudo sed -e "s/_USERNAME_/${USERNAME}/g" \
             "$(templates)/user-admin-crb.yaml" | \
         kubectl "${ACTION}" --filename -
}

function server_endpoint {
    local SERVER="$1"
    local PORT="$2"
    echo "https://${SERVER}:${PORT}"
}

function node_name {
    sed "s/\\..*//" /etc/hostname
}
function cluster_name {
    sed "s/[^\\.]*\\.//" /etc/hostname
}

function log {
    echo "$(date -uIseconds | sed s/\+.*//) [$(node_name)]" "$@"
}
function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
