#!/bin/bash

set -e

# shellcheck source=src/kube-utils
source "$(dirname "$0")/kube-utils"

USAGE="Usage: kube-pki <[User@]From> <[User@]To>"

function main {
    local FROM="$1"
    local TO="$2"
    local ARCHIVE="/tmp/pki.tgz"

    if [ -z "${FROM}" ] || [ -z "${TO}" ]; then stop "${USAGE}"; fi

    run node "${FROM}" master pki make "${ARCHIVE}"
    scp -3 "${FROM}:${ARCHIVE}" "${TO}:${ARCHIVE}"
    ssh "${FROM}" rm \\"${ARCHIVE}"
    run node "${TO}" master pki install "${ARCHIVE}"
}

main "$@"
