#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: kube-tools-ubuntu install [User]
EOF
)

function main {
    local START_TIME; START_TIME="$(start_time)"

    case "$1" in
        install) shift 1; ubuntu_install "$@" ;;
        *) stop "${USAGE}" ;;
    esac

    show_completion_time "${START_TIME}"
}

function ubuntu_install {
    local USER="${1:-ubuntu}"

    log "Preparing Ubuntu with user ${USER}..."

    sudo apt-get update
    sudo apt-get install curl \
                         socat \
                         ca-certificates \
                         apt-transport-https \
                         software-properties-common -y

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "$(ubuntu_docker_repo)"
    sudo apt-get update
    sudo apt-get install ebtables ethtool docker-ce=18.06.1~ce~3-0~ubuntu -y
    
    sudo systemctl start docker
    sudo systemctl enable docker
    
    sudo swapoff -a
    sudo sed -i "s/\\(.*\\)swap\\(.*\\)/#\\1swap\\2/" /etc/fstab
    
    sudo ln -sf /opt/bin/kube{adm,ctl,let} /usr/bin
    
    sudo adduser --disabled-password --gecos "" "${USER}" || true
    sudo usermod -aG sudo "${USER}"
    sudo usermod -aG docker "${USER}"
    
    sudo mkdir -p "/home/${USER}/.ssh"
    sudo -E cp "${HOME}/.ssh/authorized_keys" \
               "/home/${USER}/.ssh/authorized_keys" || true
    sudo chown -R "${USER}:${USER}" "/home/${USER}/.ssh"
    
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" | \
        sudo tee "/etc/sudoers.d/${USER}" > /dev/null
}

function ubuntu_docker_repo {
    printf "%b" "deb [arch=amd64] https://download.docker.com/linux/ubuntu\\n" \
                "$(lsb_release -cs)\\n" \
                "stable\\n"
}

main "$@"
