#!/bin/bash

set -e

# shellcheck source=src/kube-utils
source "$(dirname "$0")/kube-utils"

Usage="Usage: kube-pki <[SshUser@]SshAddressFrom> <[SshUser@]SshAddressTo>"

function main {
    local From="$1"
    local To="$2"
    local Archive="/tmp/pki.tgz"

    if [ -z "${From}" ] || [ -z "${To}" ]; then stop "${Usage}"; fi

    run node "${From}" master pki make "${Archive}"
    scp -3 "${From}:${Archive}" "${To}:${Archive}"
    ssh "${From}" rm \\"${Archive}"
    run node "${To}" master pki install "${Archive}"
}

main "$@"
