apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: _K8S_VERSION_
controlPlaneEndpoint: "kubernetes:6443"
apiServer:
  certSANs:
  - "_API_HOSTNAME_"
networking:
  podSubnet: "_POD_SUBNET_"
  serviceSubnet: "_SERVICE_SUBNET_"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta1
localAPIEndpoint:
  advertiseAddress: "_NODE_IP_"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- "_CLUSTER_DNS_"
