#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: kube-user create <Username> [Options]

Options
    -c|--company=<Company>
    -d|--days=<Days>
    -s|--server=<Server>
EOF
)

function main {
    local START_TIME; START_TIME="$(start_time)"

    case "$1 $2" in
        "create $2")
            local USERNAME="$2"
            if [ -z "${USERNAME}" ]; then usage; fi
            shift 2

            create_user "${USERNAME}" "$@"
            show_completion_time "${START_TIME}"
        ;;
        *) usage ;;
    esac

    show_completion_time "${START_TIME}"
}

function kubectl {
    sudo /opt/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf "$@"
}
function templates {
    echo "/etc/kubernetes/templates"
}

function create_cert_key {
    local USERNAME="$1"
    openssl genrsa -out "${USERNAME}-key.pem" 2048
}
function delete_cert_key {
    local USERNAME="$1"
    rm "${USERNAME}-key.pem" 
}
function create_cert {
    local USERNAME="$1"
    local COMPANY="$2"

    openssl req -new -key "${USERNAME}-key.pem" \
                -out "${USERNAME}.pem" \
                -subj "/CN=${USERNAME}/O=${COMPANY}"
}
function delete_cert {
    local USERNAME="$1"
    rm "${USERNAME}.pem"
}
function sign_cert {
    local USERNAME="$1"
    local DAYS="$2"

    sudo openssl x509 -req -in "${USERNAME}.pem" \
                      -CA /etc/kubernetes/pki/ca.crt \
                      -CAkey /etc/kubernetes/pki/ca.key \
                      -CAcreateserial \
                      -out "${USERNAME}.pem" \
                      -days "${DAYS}"
}

function create_kubeconfig {
    local USERNAME="$1"
    local NAMESPACE="$2"
    local SERVER="$3"
    local KUBECONFIG="${USERNAME}.conf"

    /opt/bin/kubectl config set-cluster "$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --server="$(server_endpoint "${SERVER}")" \
        --certificate-authority=/etc/kubernetes/pki/ca.crt \
        --embed-certs=true
    
    /opt/bin/kubectl config set-credentials "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --client-certificate="${USERNAME}.pem" \
        --client-key="${USERNAME}-key.pem" \
        --embed-certs=true
    
    /opt/bin/kubectl config set-context "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --cluster="$(cluster_name)" \
        --user="${USERNAME}-$(cluster_name)" \
        --namespace="${NAMESPACE}"
    
    /opt/bin/kubectl config use-context "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}"
}

function create_role_binding {
    local USERNAME="$1"

    sudo sed -e "s/_USERNAME_/${USERNAME}/g" \
             "$(templates)/rbac-user-admin-crb.yaml" | \
         kubectl apply -f -
}

function create_user {
    local USERNAME="$1"
    shift

    log "Creating user ${USERNAME}..."

    for ARG in "$@"; do
        case "${ARG}" in
            -c=*|--company=*) COMPANY="${ARG#*=}"; shift ;;
            -d=*|--days=*) DAYS="${ARG#*=}"; shift ;;
            -s=*|--server=*) SERVER="${ARG#*=}"; shift ;;
            *=*) >&2 echo "Unknown argument: ${ARG%=*}"; exit 2 ;;
            *) >&2 echo "Unknown argument: ${ARG}"; exit 2 ;;
        esac
    done
    
    COMPANY="${COMPANY:-Kubernetes}"
    DAYS="${DAYS:-365}"
    NAMESPACE="${NAMESPACE:-default}"
    SERVER="${SERVER:-k8s.$(cluster_name)}"
    
    create_cert_key "${USERNAME}"
    create_cert "${USERNAME}" "${COMPANY}"
    sign_cert "${USERNAME}" "${DAYS}"
    create_kubeconfig "${USERNAME}" "${NAMESPACE}" "${SERVER}"
    delete_cert "${USERNAME}"
    delete_cert_key "${USERNAME}"
    create_role_binding "${USERNAME}"
}

function server_endpoint {
    local SERVER="$1"
    echo "https://${SERVER}:6443"
}

function node_name {
    hostname -s
}
function cluster_name {
    hostname -d
}

function start_time {
    date +%s
}
function show_completion_time {
    local START_TIME="$1"
    local END_TIME; END_TIME="$(date +%s)"
    log "Complete in $(date -d@$((END_TIME - START_TIME)) -u +%Mm%Ss)."
}
function log {
    echo "$(date -uIseconds | sed s/\+.*//) [$(node_name)]" "$@"
}
function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
