#!/bin/bash

set -e

USAGE="Usage: kube-master-init <IP> [API IP]"

function ensure_in_hosts {
    local IP="$1"
    local HOSTNAME="$2"

    echo "[$(node)] Ensuring $IP $HOSTNAME is in /etc/hosts..."
    grep -q $HOSTNAME /etc/hosts && \
        sudo sed -i "s/.* \($HOSTNAME\)/$IP    \1/" /etc/hosts || \
        sudo sed -i "$ a $IP    $HOSTNAME" /etc/hosts
}

function delete_from_hosts {
    local IP="$1"
    local HOSTNAME="$2"

    echo "[$(node)] Deleting $IP $HOSTNAME from /etc/hosts..."
    sudo sed -i "/$IP    $HOSTNAME/d" /etc/hosts
}

function make_pki {
    local ARCHIVE="$1"

    echo "[$(node)] Making PKI archive $ARCHIVE..."
    mkdir -p kubernetes/pki/etcd
    sudo cp /etc/kubernetes/pki/{ca.{crt,key},sa.{key,pub}} kubernetes/pki
    sudo cp /etc/kubernetes/pki/front-proxy-ca.{crt,key} kubernetes/pki
    sudo cp /etc/kubernetes/pki/etcd/ca.{crt,key} kubernetes/pki/etcd
    sudo cp /etc/kubernetes/admin.conf kubernetes

    sudo chown -R $USER:$USER kubernetes
    tar zcf $ARCHIVE kubernetes
    rm -rf kubernetes
}

function install_pki {
    local ARCHIVE="$1"

    echo "[$(node)] Installing existing PKI from $ARCHIVE..."
    sudo tar xf "$ARCHIVE" -C /etc
    sudo chown -R root:root /etc/kubernetes
    #rm "$ARCHIVE"
}

function etcd_cluster {
    local KUBECTL="$1"
    JP=`printf %b \
        '{range .items[*]}' \
            '{.spec.nodeName}{"=https://"}{.status.podIP}{":2380,"}' \
        '{end}'`
    sudo $KUBECTL get pods --output jsonpath="$JP"
}

function etcd_hostname {
    local KUBECTL="$1"
    sudo $KUBECTL get pods --output jsonpath='{.items[0].spec.nodeName}'
}

function etcd_ip {
    local KUBECTL="$1"
    sudo $KUBECTL get pods --output jsonpath='{.items[0].status.podIP}'
}

if [ -z "$1" ]; then
    >&2 echo "$USAGE"
    exit 2
fi

IP="$1"
API_IP="${2:-$IP}" # set to $2 if $2 is set, otherwise to $IP

#LB_IP="${2#*:}"
#LB_IP=${LB_IP:-$IP}
#LB_IFACE="${2%:*}"

K8S_VERSION="$(/opt/bin/kubelet --version | sed 's/.* //')"

CLUSTER="$(hostname -d)"

HOSTNAME="$(hostname -f)"
API_HOSTNAME=k8s.$CLUSTER

KUBECTL="kubectl --kubeconfig /etc/kubernetes/admin.conf"
KUBECTL_ETCD="$KUBECTL --namespace kube-system --selector component=etcd"

ensure_in_hosts $IP $HOSTNAME
ensure_in_hosts $LB_IP $LB_HOSTNAME

if [ ! -f "kube-pki.tgz" ]; then
    ETCD_CLUSTER=""
    ETCD_STATE="new"
else
    install_pki kube-pki.tgz

    ETCD_CLUSTER=$(etcd_cluster "$KUBECTL_ETCD")
    ETCD_STATE="existing"
fi

sed -i -e s/__K8S_VERSION__/$K8S_VERSION/g \
       -e s/__API_HOSTNAME__/$API_HOSTNAME/g \
       -e s/__CLUSTER__/$CLUSTER/g \
       -e s/__HOSTNAME__/$HOSTNAME/g \
       -e s/__IP__/$IP/g \
       -e s\\__ETCD_CLUSTER__\\$ETCD_CLUSTER\\g \
       -e s/__ETCD_STATE__/$ETCD_STATE/g kubeadm-config.yaml

CONFIG="--config kubeadm-config.yaml"
ALPHA_PHASE="kubeadm alpha phase"

if [ "$ETCD_STATE" = "new" ]; then
    echo "[$(node)] Initialising $CLUSTER..."
    sudo kubeadm init $CONFIG

    echo "[$(node)] Installing Calico..."
    sudo $KUBECTL apply -f calico-rbac-kdd.yaml
    sudo $KUBECTL apply -f calico.yaml

#   if [ "$IP" != "$LB_IP" ]; then
#       echo "[$(node)] Installing Keepalived..."
#       sed -i -e s/__LB_IP__/$LB_IP/ \
#              -e s/__LB_IFACE__/$LB_IFACE/ \
#              -e s/__LB_PASSWORD__/"$(openssl rand -base64 8)"/ keepalived.yaml
#       sudo $KUBECTL apply -f keepalived.yaml
#   fi
else
    echo "[$(node)] Joining $CLUSTER..."

    sudo $ALPHA_PHASE certs all $CONFIG
    sudo $ALPHA_PHASE kubelet config write-to-disk $CONFIG
    sudo $ALPHA_PHASE kubelet write-env-file $CONFIG
    sudo $ALPHA_PHASE kubeconfig kubelet $CONFIG
    sudo systemctl start kubelet

    ETCD_HOSTNAME=$(etcd_hostname "$KUBECTL_ETCD")
    ETCD_IP=$(etcd_ip "$KUBECTL_ETCD")

    echo "[$(node)] Joining etcd $ETCD_HOSTNAME ($ETCD_IP)..."
    sudo $KUBECTL --namespace kube-system \
                  exec etcd-${ETCD_HOSTNAME} -- \
             etcdctl --ca-file /etc/kubernetes/pki/etcd/ca.crt \
                     --key-file /etc/kubernetes/pki/etcd/peer.key \
                     --cert-file /etc/kubernetes/pki/etcd/peer.crt \
                     --endpoints=https://${ETCD_IP}:2379 \
                 member add $HOSTNAME https://${IP}:2380

    sudo $ALPHA_PHASE etcd local $CONFIG
    sudo $ALPHA_PHASE kubeconfig all $CONFIG
    sudo $ALPHA_PHASE controlplane all $CONFIG
    sudo $ALPHA_PHASE kubelet config annotate-cri $CONFIG
    sudo $ALPHA_PHASE mark-master $CONFIG
fi
