#!/bin/bash

set -e

function usage {
    >&2 echo "Usage: kube-pki <PKI Archive> <From IP> <To IP>"
    exit 2
}

[ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ] || usage

ARCHIVE="$1"
FROM="core@$2"
TO="core@$3"

ssh "$FROM" bash -s < ./scripts/kube-node master pki make "$ARCHIVE"
scp "$FROM:$ARCHIVE" "./$ARCHIVE"
scp "./$ARCHIVE" "$TO:$ARCHIVE"
ssh "$FROM" rm "$ARCHIVE"
rm "$ARCHIVE"
