apiVersion: v1
kind: Namespace
metadata:
  name: kubealived-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubealived-config
  namespace: kubealived-system
data:
  keepalived.conf: |
    vrrp_instance VI_1 {
        state MASTER
        interface _IFACE_
        virtual_router_id _VRID_
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass _PASSWORD_
        }
        virtual_ipaddress {
            _IP_
        }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kubealived
  namespace: kubealived-system
  labels:
    app: kubealived
spec:
  selector:
    matchLabels:
      app: kubealived
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubealived
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      hostNetwork: true
      containers:
      - name: kubealived
        image: quay.io/openvnf/kubealived:1.2.0
        args: ["-nl"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: config
          mountPath: /etc/keepalived
      volumes:
      - name: config
        configMap:
          name: kubealived-config
