apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni
  namespace: kube-system
data:
  plugins: multus-cni,macvlan,ipvlan
  configs: 05-multus-cni.conf
  manifests: multus-cni-crd.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni-configs
  namespace: kube-system
data:
  05-multus-cni.conf: |
    {"name": "multus-cni",
     "cniVersion":"0.1.0",
     "type": "multus-cni",
     "kubeconfig": "/etc/kubernetes/kubelet.conf",
     "delegates": [
       __10-calico.conflist__
     ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni-manifests
  namespace: kube-system
data:
  multus-cni-crd.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: multus-cni-${NODE_HOSTNAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: multus-cni-crd
    subjects:
    - kind: User
      name: system:node:${NODE_HOSTNAME}
      apiGroup: rbac.authorization.k8s.io
