#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: cennsonic-user <Action> <Username> [Options]

Actions
    create
    delete

Options
    -a, --admin
    -c, --company=<Company>
    -d, --days=<Days>
    -s, --server=<Server>
        --ca-cert=<CA Cert Path>
        --ca-cert-key=<CA Cert Key Path>
EOF
)

function main {
    case "$1 $2" in
        "create $2"|\
        "delete $2")
            local ACTION="$1"
            local USERNAME="$2"
            shift 2

            if [ -z "${USERNAME}" ]; then usage; fi
            "${ACTION}_user" "${USERNAME}" "$@"
        ;;
        *) usage ;;
    esac
}

function ca_cert {
    echo "/etc/kubernetes/ssl/ca.pem"
}
function ca_cert_key {
    echo "/etc/kubernetes/ssl/ca-key.pem"
}
function templates {
    echo "/etc/kubernetes"
}
function kubectl {
    sudo /usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf "$@"
}

function create_user {
    local USERNAME="$1"
    shift

    for ARG in "$@"; do
        case "${ARG}" in
            -a|--admin) local ADMIN=true; shift ;;
            -c=*|--company=*) local COMPANY="${ARG#*=}"; shift ;;
            -d=*|--days=*) local DAYS="${ARG#*=}"; shift ;;
            -s=*|--server=*) local SERVER="${ARG#*=}"; shift ;;
                 --ca-cert=*) local CA_CERT="${ARG#*=}"; shift ;;
                 --ca-cert-key=*) local CA_CERT_KEY="${ARG#*=}"; shift ;;
            *=*) >&2 echo "Unknown argument: ${ARG%=*}"; exit 2 ;;
            *) >&2 echo "Unknown argument: ${ARG}"; exit 2 ;;
        esac
    done

    log "Creating user ${USERNAME}..."

    ADMIN="${ADMIN:-false}"
    COMPANY="${COMPANY:-Kubernetes}"
    DAYS="${DAYS:-365}"
    NAMESPACE="${NAMESPACE:-default}"
    SERVER="${SERVER:-k8s.$(cluster_name)}"
    CA_CERT="${CA_CERT:-$(ca_cert)}"
    CA_CERT_KEY="${CA_CERT_KEY:-$(ca_cert_key)}"

    create_cert_key "${USERNAME}"
    create_cert "${USERNAME}" "${COMPANY}"
    sign_cert "${USERNAME}" "${DAYS}" "${CA_CERT}" "${CA_CERT_KEY}"
    create_kubeconfig "${USERNAME}" "${NAMESPACE}" "${SERVER}" "${CA_CERT}"
    delete_cert "${USERNAME}"
    delete_cert_key "${USERNAME}"

    if "${ADMIN}"; then create_admin_binding "${USERNAME}"; fi
}
function delete_user {
    local USERNAME="$1"
    shift

    log "Deleting user ${USERNAME}..."
    delete_admin_binding "${USERNAME}"
}

function create_cert_key {
    local USERNAME="$1"
    openssl genrsa -out "${USERNAME}-key.pem" 2048
}
function delete_cert_key {
    local USERNAME="$1"
    rm "${USERNAME}-key.pem" 
}
function create_cert {
    local USERNAME="$1"
    local COMPANY="$2"

    openssl req -new -key "${USERNAME}-key.pem" \
                -out "${USERNAME}.pem" \
                -subj "/CN=${USERNAME}/O=${COMPANY}"
}
function delete_cert {
    local USERNAME="$1"
    rm "${USERNAME}.pem"
}
function sign_cert {
    local USERNAME="$1"
    local DAYS="$2"
    local CA_CERT="$3"
    local CA_CERT_KEY="$4"

    sudo openssl x509 -req -in "${USERNAME}.pem" \
                      -CA "${CA_CERT}" \
                      -CAkey "${CA_CERT_KEY}" \
                      -CAcreateserial \
                      -out "${USERNAME}.pem" \
                      -days "${DAYS}"
}

function create_kubeconfig {
    local USERNAME="$1"
    local NAMESPACE="$2"
    local SERVER="$3"
    local CA_CERT="$4"
    local KUBECONFIG="${USERNAME}.conf"

    /usr/local/bin/kubectl config set-cluster "$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --server="$(server_endpoint "${SERVER}")" \
        --certificate-authority="${CA_CERT}" \
        --embed-certs=true
    
    /usr/local/bin/kubectl config set-credentials "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --client-certificate="${USERNAME}.pem" \
        --client-key="${USERNAME}-key.pem" \
        --embed-certs=true
    
    /usr/local/bin/kubectl config set-context "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}" \
        --cluster="$(cluster_name)" \
        --user="${USERNAME}-$(cluster_name)" \
        --namespace="${NAMESPACE}"
    
    /usr/local/bin/kubectl config use-context "${USERNAME}-$(cluster_name)" \
        --kubeconfig="${KUBECONFIG}"
}
function create_admin_binding {
    admin_binding apply "$@"
}
function delete_admin_binding {
    admin_binding delete "$@"
}
function admin_binding {
    local ACTION="$1"
    local USERNAME="$2"
    local MANIFEST="$(print "%b")"

    curl -sL "$(admin_binding_manifest)" | \
        sed -e "s/_USERNAME_/${USERNAME}/g" | \
            kubectl "${ACTION}" --filename -
}
function admin_binding_manifest {
    printf "%b" "https://raw.githubusercontent.com/travelping/cennsonic/" \
                "master/components/users/user-admin-crb.yaml"
}

function server_endpoint {
    local SERVER="$1"
    echo "https://${SERVER}:6443"
}

function node_name {
    cat /etc/hostname | sed "s/\..*//"
}
function cluster_name {
    cat /etc/hostname | sed "s/[^\.]*.//"
}

function log {
    echo "$(date -uIseconds | sed s/\+.*//) [$(node_name)]" "$@"
}
function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
