#!/bin/bash

set -e

# shellcheck source=src/kube-utils
source "$(dirname "$0")/kube-utils"

Usage=$(cat <<EOF
Usage: kube-tools-ubuntu install [Options]

Options
    -u,--setup-user=<User>
EOF
)

function main {
    local StartTime; StartTime="$(start_time)"

    case "$1" in
        install) shift 1; ubuntu_install "$@" ;;
        *) stop "${Usage}" ;;
    esac

    show_completion_time "${StartTime}"
}

function ubuntu_install {
    log "Preparing Ubuntu..."

    local Arg
    for Arg in "$@"; do
        case "${Arg}" in
            -u=*|--setup-user=*) local User="${Arg#*=}"; shift ;;
            *) stop unknown-option "${Arg}" ;;
        esac
    done

    sudo apt-get update
    sudo apt-get install curl \
                         socat \
                         ca-certificates \
                         apt-transport-https \
                         software-properties-common -y

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "$(ubuntu_docker_repo)"
    sudo apt-get update
    sudo apt-get install ebtables ethtool docker-ce=18.06.1~ce~3-0~ubuntu -y

    sudo systemctl start docker
    sudo systemctl enable docker

    sudo swapoff -a
    sudo sed -i "s/\\(.*\\)swap\\(.*\\)/#\\1swap\\2/" /etc/fstab

    sudo ln -sf /opt/bin/kube{adm,ctl,let} /usr/bin

    if [ -n "${User}" ]; then
        log "Creating user ${User}..."

        sudo adduser --disabled-password --gecos "" "${User}" || true
        sudo usermod -aG sudo "${User}"
        sudo usermod -aG docker "${User}"

        sudo mkdir -p "/home/${User}/.ssh"
        sudo -E cp "${HOME}/.ssh/authorized_keys" \
                   "/home/${User}/.ssh/authorized_keys" || true
        sudo chown -R "${User}:${User}" "/home/${User}/.ssh"

        echo "${User} ALL=(ALL) NOPASSWD: ALL" |
            sudo tee "/etc/sudoers.d/${User}" > /dev/null
    fi
}

function ubuntu_docker_repo {
    printf "%b" "deb [arch=amd64] https://download.docker.com/linux/ubuntu\\n" \
                "$(lsb_release -cs)\\n" \
                "stable\\n"
}

main "$@"
