#!/bin/bash

set -e

# shellcheck source=src/kube-utils
source "$(dirname "$0")/kube-utils"

Usage=$(cat <<EOF
Usage: kube <Command> <[SshUser@]SshAddress> [Args]

Commands
    tools[-<ubuntu|centos>]
    node
    user
    pki
EOF
)

function main {
    local Unit="$1"

    case "${Unit}" in
        pki|make)
            shift 1
            "$(workdir)/kube-${Unit}" "$@"
        ;;
        *)
            local Target="$2"
            if [ -z "${Target}" ]; then stop "${Usage}"; fi

            shift 2
            run "${Unit}" "${Target}" "$@"
        ;;
    esac
}

main "$@"
