#!/bin/bash

set -e

function usage {
    >&2 echo "Usage: kube-pki <PKI Archive> <From IP> <To IP>"
    exit 2
}

ARCHIVE="$1"
FROM="$2"
TO="$3"

if [ -z "${ARCHIVE}" ] || [ -z "${FROM}" ] || [ -z "${TO}" ]; then usage; fi

FROM="core@${FROM}"
TO="core@${TO}"

ssh "${FROM}" bash -s < ./scripts/kube-node master pki make "${ARCHIVE}"
scp "${FROM}:$ARCHIVE" "./${ARCHIVE}"
scp "./${ARCHIVE}" "${TO}:${ARCHIVE}"
ssh "${FROM}" rm \\"${ARCHIVE}\\"
rm "${ARCHIVE}"
